import { ArrowRight, BadgeCheck, ChevronRight, ShieldCheck, ShoppingCart, Sparkles, Star, Users, Zap } from "lucide-react";
import Link from "next/link";
import { categories, products, money } from "@/lib/store";
import AddToCartButton from "@/components/AddToCartButton";

export default function Home() {
  return <main>
    <section className="hero"><div className="hero-glow glow-one"/><div className="hero-glow glow-two"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> Your trusted digital marketplace</div><h1>Everything digital.<br/><span>Simple, fast & secure.</span></h1><p>Discover digital products, subscriptions, gift cards and services from trusted sellers — all in one place.</p><div className="hero-buttons"><Link href="/marketplace" className="primary-btn">Explore marketplace <ArrowRight size={18}/></Link><Link href="/how-it-works" className="secondary-btn">How it works</Link></div><div className="hero-trust"><div className="avatars"><i>JD</i><i>AM</i><i>SK</i><i>+</i></div><div><strong>50k+ happy customers</strong><small>Rated 4.9/5 across thousands of orders</small></div></div></div><div className="hero-card"><div className="floating-card card-a"><div className="mini-icon purple">✦</div><div><b>Instant delivery</b><small>Available 24/7</small></div><BadgeCheck size={18}/></div><div className="market-card"><div className="market-top"><span>Trending now</span><span className="live-dot">● Live</span></div><div className="market-product"><div className="product-art main-art"><Sparkles size={42}/></div><div className="market-info"><span>Premium</span><h3>Digital subscription</h3><div className="stars">★★★★★ <small>4.9</small></div><div className="market-price">$8.99 <del>$12.99</del></div></div></div><div className="secure-row"><ShieldCheck size={17}/> Verified seller <span>•</span> Instant delivery</div><Link className="buy-btn" href="/products/premium-streaming-access">Get it now <ArrowRight size={17}/></Link></div><div className="floating-card card-b"><div className="mini-icon green"><Zap size={17}/></div><div><b>Order completed</b><small>Just now</small></div><span className="check">✓</span></div></div></div></section>
    <section className="category-section" id="categories"><div className="container"><div className="section-heading"><div><span className="section-kicker">BROWSE</span><h2>Shop by category</h2></div><Link href="/categories">View all <ChevronRight size={17}/></Link></div><div className="category-grid">{categories.map(cat=><Link className="category-card" href={`/marketplace?category=${encodeURIComponent(cat.name)}`} key={cat.name}><span className="cat-icon">{cat.icon}</span><div><h3>{cat.name}</h3><p>{cat.count} products</p></div><ChevronRight className="cat-arrow" size={18}/></Link>)}</div></div></section>
    <section className="featured" id="featured"><div className="container"><div className="section-heading"><div><span className="section-kicker">CURATED FOR YOU</span><h2>Featured products</h2></div><Link href="/featured">See all products <ChevronRight size={17}/></Link></div><div className="product-grid">{products.map(p=><article className="product-card" key={p.slug}><Link href={`/products/${p.slug}`}><div className={`product-image ${p.tone}`}><span className="product-badge">{p.badge}</span><div className="product-symbol">{p.tone==="orange"?"◇":p.tone==="green"?"⚡":"✦"}</div></div></Link><div className="product-body"><span className="product-category">{p.category}</span><h3>{p.title}</h3><div className="rating"><Star size={14} fill="currentColor"/> {p.rating}<span>• popular</span></div><div className="product-bottom"><div><strong>{money(p.price)}</strong>{p.old&&<del>{money(p.old)}</del>}</div><AddToCartButton product={p} compact/></div></div></article>)}</div></div></section>
    <section className="why" id="how"><div className="container why-grid"><div><span className="section-kicker">WHY MASAYOSHIHUB</span><h2>Built around a better<br/>way to shop digital.</h2><p>We keep the buying experience straightforward: verified sellers, transparent pricing and delivery that happens when you need it.</p><Link className="primary-btn small" href="/marketplace">Start shopping <ArrowRight size={17}/></Link></div><div className="benefits"><div><span className="benefit-icon"><ShieldCheck/></span><div><h3>Secure by design</h3><p>Your account and checkout experience are protected with modern security practices.</p></div></div><div><span className="benefit-icon"><Zap/></span><div><h3>Instant delivery</h3><p>Most digital orders are designed for automatic delivery after successful payment.</p></div></div><div><span className="benefit-icon"><Users/></span><div><h3>Trusted community</h3><p>Shop confidently with seller ratings and customer feedback.</p></div></div></div></div></section>
    <section className="cta"><div className="container cta-inner"><div><span className="section-kicker">READY WHEN YOU ARE</span><h2>Find your next digital essential.</h2><p>Browse the marketplace from one clean interface.</p></div><Link className="primary-btn" href="/marketplace">Explore marketplace <ArrowRight size={18}/></Link></div></section>
    <footer><div className="container footer-grid"><div><Link className="brand" href="/"><span className="brand-mark">M</span><span>Masayoshi<span>Hub</span></span></Link><p>A modern digital marketplace for products, subscriptions and services.</p></div><div><h4>Marketplace</h4><Link href="/categories">Categories</Link><Link href="/featured">Featured</Link><Link href="/marketplace">All products</Link><Link href="/cart"><ShoppingCart size={12}/> Cart</Link></div><div><h4>Company</h4><Link href="/about">About</Link><Link href="/contact">Contact</Link><Link href="/help">Help center</Link></div><div><h4>Legal</h4><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link><Link href="/refund-policy">Refund policy</Link></div></div><div className="container footer-bottom"><span>© 2026 MasayoshiHub. All rights reserved.</span><span>Made for a better digital shopping experience.</span></div></footer>
  </main>;
}
