export const categories = [
  {
    name: "Digital Accounts",
    icon: "◉",
    count: "Available",
  },
  {
    name: "Subscriptions",
    icon: "✦",
    count: "Unlimited",
  },
  {
    name: "Gift Cards",
    icon: "🎁",
    count: "Unavailable",
  },
  {
    name: "Software",
    icon: "▣",
    count: "Unavailable",
  },
  {
    name: "Games",
    icon: "◈",
    count: "Unavailable",
  },
  {
    name: "Services",
    icon: "⚡",
    count: "Unlimited",
  },
];

export const products = [
  {
    id: "facebook-account",
    description: "Facebook accounts available for purchase.",
    slug: "facebook-account",
    title: "Facebook Accounts",
    category: "Digital Accounts",
    price: 4999,
    old: 5999,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "instagram-account",
    description: "Instagram accounts available for purchase.",
    slug: "instagram-account",
    title: "Instagram Accounts",
    category: "Digital Accounts",
    price: 4999,
    old: 5999,
    tone: "purple",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "tiktok-account",
    description: "TikTok accounts available for purchase.",
    slug: "tiktok-account",
    title: "TikTok Accounts",
    category: "Digital Accounts",
    price: 3499,
    old: 4499,
    tone: "orange",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "whatsapp-account",
    description: "WhatsApp accounts available for purchase.",
    slug: "whatsapp-account",
    title: "WhatsApp Accounts",
    category: "Digital Accounts",
    price: 4999,
    old: 5999,
    tone: "green",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "x-account",
    description: "X accounts available for purchase.",
    slug: "x-account",
    title: "X Accounts",
    category: "Digital Accounts",
    price: 8999,
    old: 9999,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "netflix-subscription",
    description: "Netflix subscriptions available.",
    slug: "netflix-subscription",
    title: "Netflix Subscription",
    category: "Subscriptions",
    price: 10000,
    old: 12000,
    tone: "purple",
    badge: "Unlimited",
    rating: 4.9,
  },
  {
    id: "social-media-boosting",
    description: "Social media follower, likes and comments boosting services.",
    slug: "social-media-boosting",
    title: "Social Media Boosting",
    category: "Services",
    price: 5000,
    old: 6000,
    tone: "orange",
    badge: "Unlimited",
    rating: 4.8,
  },
];
