export const categories = [
  {
    name: "Buy Accounts",
    icon: "◉",
    count: "Unlimited",
  },
  {
    name: "Subscriptions",
    icon: "✦",
    count: "Unlimited",
  },
  {
    name: "Gift Cards",
    icon: "🎁",
    count: "Unavailable",
  },
  {
    name: "Software",
    icon: "▣",
    count: "Unavailable",
  },
  {
    name: "Games",
    icon: "◈",
    count: "Unavailable",
  },
  {
    name: "Services",
    icon: "⚡",
    count: "Unlimited",
  },
];

export const products = [
  {
    id: "facebook-new",
    description: "New Facebook account",
    slug: "facebook-new",
    title: "New Facebook Account",
    category: "Buy Accounts",
    subcategory: "Facebook",
    price: 1500,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "facebook-aged-friends",
    description: "Aged Facebook account with friends",
    slug: "facebook-aged-friends",
    title: "Aged Facebook with Friends",
    category: "Buy Accounts",
    subcategory: "Facebook",
    price: 3999,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "facebook-aged-page",
    description: "Aged Facebook account with Page",
    slug: "facebook-aged-page",
    title: "Aged Facebook with Page",
    category: "Buy Accounts",
    subcategory: "Facebook",
    price: 4999,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "facebook-germany",
    description: "8-15 years Germany Facebook account with 0-50 friends and active marketplace",
    slug: "facebook-germany",
    title: "8-15 Years Germany Facebook",
    category: "Buy Accounts",
    subcategory: "Facebook",
    price: 8999,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "facebook-europe-asia",
    description: "Europe and Asian Facebook account with 1,000-5,000 friends and active marketplace",
    slug: "facebook-europe-asia",
    title: "Europe & Asian Facebook 1,000-5,000 Friends",
    category: "Buy Accounts",
    subcategory: "Facebook",
    price: 9999,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },

  {
    id: "instagram-200",
    description: "10-15 years Instagram account with 200+ followers",
    slug: "instagram-200",
    title: "Instagram 10-15 Years • 200+ Followers",
    category: "Buy Accounts",
    subcategory: "Instagram",
    price: 3999,
    old: 0,
    tone: "purple",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "instagram-500",
    description: "6-10 years Instagram account with 500+ followers",
    slug: "instagram-500",
    title: "Instagram 6-10 Years • 500+ Followers",
    category: "Buy Accounts",
    subcategory: "Instagram",
    price: 4999,
    old: 0,
    tone: "purple",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "instagram-1000",
    description: "10-15 years Instagram account with 1,000+ followers",
    slug: "instagram-1000",
    title: "Instagram 10-15 Years • 1,000+ Followers",
    category: "Buy Accounts",
    subcategory: "Instagram",
    price: 5999,
    old: 0,
    tone: "purple",
    badge: "Available",
    rating: 4.8,
  },

  {
    id: "tiktok-220",
    description: "Aged real Europe TikTok account with 220+ followers",
    slug: "tiktok-220",
    title: "TikTok Europe • 220+ Followers",
    category: "Buy Accounts",
    subcategory: "TikTok",
    price: 4999,
    old: 0,
    tone: "orange",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "tiktok-600",
    description: "Aged real Europe TikTok account with 600+ followers",
    slug: "tiktok-600",
    title: "TikTok Europe • 600+ Followers",
    category: "Buy Accounts",
    subcategory: "TikTok",
    price: 5999,
    old: 0,
    tone: "orange",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "tiktok-800",
    description: "Aged real Europe TikTok account with 800+ followers",
    slug: "tiktok-800",
    title: "TikTok Europe • 800+ Followers",
    category: "Buy Accounts",
    subcategory: "TikTok",
    price: 7499,
    old: 0,
    tone: "orange",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "tiktok-1000",
    description: "Aged real Europe TikTok account with 1,000+ followers",
    slug: "tiktok-1000",
    title: "TikTok Europe • 1,000+ Followers",
    category: "Buy Accounts",
    subcategory: "TikTok",
    price: 8999,
    old: 0,
    tone: "orange",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "tiktok-2000",
    description: "Aged real Europe TikTok account with 2,000+ followers",
    slug: "tiktok-2000",
    title: "TikTok Europe • 2,000+ Followers",
    category: "Buy Accounts",
    subcategory: "TikTok",
    price: 13999,
    old: 0,
    tone: "orange",
    badge: "Available",
    rating: 4.8,
  },

  {
    id: "twitter-10-50",
    description: "Europe Twitter account with 10-50 followers",
    slug: "twitter-10-50",
    title: "Europe Twitter • 10-50 Followers",
    category: "Buy Accounts",
    subcategory: "X / Twitter",
    price: 3999,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "twitter-90-100",
    description: "Europe Twitter account with 90-100 followers",
    slug: "twitter-90-100",
    title: "Europe Twitter • 90-100 Followers",
    category: "Buy Accounts",
    subcategory: "X / Twitter",
    price: 4499,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "twitter-100-200",
    description: "Europe Twitter account with 100-200 followers",
    slug: "twitter-100-200",
    title: "Europe Twitter • 100-200 Followers",
    category: "Buy Accounts",
    subcategory: "X / Twitter",
    price: 4999,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "twitter-200-500",
    description: "Europe Twitter account with 200-500 followers and nice profile",
    slug: "twitter-200-500",
    title: "Europe Twitter • 200-500 Followers",
    category: "Buy Accounts",
    subcategory: "X / Twitter",
    price: 5999,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "twitter-500",
    description: "Europe Twitter account with 500+ followers and nice profile",
    slug: "twitter-500",
    title: "Europe Twitter • 500+ Followers",
    category: "Buy Accounts",
    subcategory: "X / Twitter",
    price: 9499,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },

  {
    id: "hotmail-usa",
    description: "USA aged Hotmail account",
    slug: "hotmail-usa",
    title: "USA Aged Hotmail",
    category: "Buy Accounts",
    subcategory: "Mails",
    price: 499,
    old: 0,
    tone: "green",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "gmx-usa",
    description: "USA GMX email account",
    slug: "gmx-usa",
    title: "USA GMX Mail",
    category: "Buy Accounts",
    subcategory: "Mails",
    price: 399,
    old: 0,
    tone: "green",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "mailcom-usa",
    description: "Aged USA Mail.com email account",
    slug: "mailcom-usa",
    title: "Aged USA Mail.com",
    category: "Buy Accounts",
    subcategory: "Mails",
    price: 399,
    old: 0,
    tone: "green",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "gmail-aged",
    description: "Aged Gmail account",
    slug: "gmail-aged",
    title: "Aged Gmail Account",
    category: "Buy Accounts",
    subcategory: "Mails",
    price: 2499,
    old: 0,
    tone: "green",
    badge: "Available",
    rating: 4.8,
  },

  {
    id: "whatsapp-number",
    description: "Foreign WhatsApp number",
    slug: "whatsapp-number",
    title: "WhatsApp Foreign Number",
    category: "Buy Accounts",
    subcategory: "Foreign Numbers",
    price: 4999,
    old: 0,
    tone: "green",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "signal-number",
    description: "Foreign Signal number",
    slug: "signal-number",
    title: "Signal Foreign Number",
    category: "Buy Accounts",
    subcategory: "Foreign Numbers",
    price: 2499,
    old: 0,
    tone: "green",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "telegram-number",
    description: "Foreign Telegram number",
    slug: "telegram-number",
    title: "Telegram Foreign Number",
    category: "Buy Accounts",
    price: 3999,
    old: 0,
    tone: "green",
    badge: "Available",
    rating: 4.8,
  },

  {
    id: "nordvpn",
    description: "NordVPN 1 year subscription",
    slug: "nordvpn",
    title: "NordVPN • 1 Year",
    category: "VPN Services",
    subcategory: "VPNs",
    price: 17499,
    old: 0,
    tone: "purple",
    badge: "Available",
    rating: 4.9,
  },
  {
    id: "pia-vpn",
    description: "PIA VPN 1 year subscription",
    slug: "pia-vpn",
    title: "PIA VPN • 1 Year",
    category: "VPN Services",
    subcategory: "VPNs",
    price: 12499,
    old: 0,
    tone: "blue",
    badge: "Available",
    rating: 4.8,
  },
  {
    id: "expressvpn",
    description: "ExpressVPN 1 month subscription",
    slug: "expressvpn",
    title: "ExpressVPN • 1 Month",
    category: "VPN Services",
    subcategory: "VPNs",
    price: 4999,
    old: 0,
    tone: "orange",
    badge: "Available",
    rating: 4.8,
  },
    },
  {
    id: "social-media-boosting",
    description: "TikTok, Instagram and Facebook followers, likes, views and shares.",
    slug: "social-media-boosting",
    title: "Social Media Boosting",
    category: "Services",
    subcategory: "Social Media",
    price: 599,
    old: 0,
    tone: "purple",
    badge: "Available",
    rating: 4.8,
  },
];

export type Product = (typeof products)[number];
];

export type Product = (typeof products)[number];

export function money(value: number) {
  return `₦${value.toLocaleString("en-NG")}`;
}

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
